import Head from "next/head";

export default function Home() {
  return (
    <div className="flex min-h-screen justify-center pt-10">
      <Head>
        <title>Runes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="gradient-text my-1 p-2 text-6xl font-extrabold">
        Cool App
      </div>
    </div>
  );
}
